services:
  mongo:
    image: mongo:6
    container_name: demo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"  

volumes:
  mongo_data:
